export const servicesData = {
  "roof-replacement": {
    title: "Roof Replacement",
    emoji: "🏠",
    color: "#FF4D2E",
    tagline: "Complete Roof Replacement",
    heroTitle: "Premium Roof Replacement Done Right",
    heroDescription: "Complete tear-off and installation of a brand new roof system using premium materials and expert craftsmanship. Lifetime warranty included.",
    quickBenefits: ["1-2 Day Installation", "Lifetime Warranty", "Premium Materials", "Free Inspection"],
    included: [
      { title: "Complete Tear-Off", description: "Full removal of old roofing materials down to the decking." },
      { title: "Decking Inspection", description: "We check and replace any damaged plywood at no extra charge." },
      { title: "Premium Underlayment", description: "Synthetic waterproof barrier protects against leaks." },
      { title: "Architectural Shingles", description: "GAF Timberline HDZ premium dimensional shingles." },
      { title: "New Flashing & Vents", description: "All metal flashing and ventilation systems replaced." },
      { title: "Cleanup & Disposal", description: "Complete cleanup with magnetic nail sweep included." },
    ],
    process: [
      { title: "Free Inspection", description: "We inspect your roof and provide detailed assessment." },
      { title: "Custom Quote", description: "Transparent pricing with no hidden fees." },
      { title: "Installation", description: "Our crew installs your new roof in 1-2 days." },
      { title: "Final Walkthrough", description: "We review the completed work with you." },
    ],
    faqs: [
      { q: "How long does a roof replacement take?", a: "Most residential roof replacements are completed in 1-2 days depending on size and weather conditions." },
      { q: "What materials do you use?", a: "We use premium GAF Timberline HDZ architectural shingles, synthetic underlayment, and aluminum flashing — top-quality materials backed by manufacturer warranties." },
      { q: "Do you offer financing?", a: "Yes! We offer 0% financing for qualified homeowners. Most customers get approved in 5 minutes." },
      { q: "What warranty do you provide?", a: "Lifetime workmanship warranty from us, plus full manufacturer material warranty (up to 50 years)." },
      { q: "Will my insurance cover this?", a: "If your roof was damaged by storms, hail, or wind, your insurance may cover replacement. We help with insurance claims at no extra cost." },
      { q: "Do you clean up after the job?", a: "Absolutely. We do complete cleanup including magnetic nail sweeps to ensure your property is spotless." },
    ],
  },

  "roof-repair": {
    title: "Roof Repair",
    emoji: "🔨",
    color: "#FFB800",
    tagline: "Fast Reliable Repairs",
    heroTitle: "Expert Roof Repair Services",
    heroDescription: "Fast, reliable repairs for leaks, missing shingles, storm damage, and more. Most repairs completed in a single visit.",
    quickBenefits: ["Same-Day Service", "All Roof Types", "Fair Pricing", "5-Year Warranty"],
    included: [
      { title: "Leak Detection", description: "Professional moisture testing to find the source." },
      { title: "Shingle Replacement", description: "Color-matched shingles for seamless repairs." },
      { title: "Flashing Repair", description: "Fix damaged flashing around chimneys and vents." },
      { title: "Storm Damage", description: "Quick repair of hail, wind, and storm damage." },
      { title: "Emergency Tarping", description: "Temporary protection until full repair is complete." },
      { title: "Detailed Report", description: "Photo documentation of all repairs performed." },
    ],
    process: [
      { title: "Quick Inspection", description: "We assess the damage and identify all issues." },
      { title: "Honest Quote", description: "Fair pricing with no surprise charges." },
      { title: "Fast Repair", description: "Most repairs completed same day." },
      { title: "Quality Check", description: "We test and verify all repairs are watertight." },
    ],
    faqs: [
      { q: "How quickly can you respond?", a: "We offer same-day service for most repairs and 24/7 emergency response for urgent issues like active leaks." },
      { q: "Can you repair my old roof?", a: "Yes! We repair roofs of all ages and materials. We'll give you honest advice if replacement is more cost-effective." },
      { q: "Do you provide warranties on repairs?", a: "Yes, all repairs come with a 5-year workmanship warranty." },
      { q: "What does a roof repair cost?", a: "Repair costs vary based on damage extent. Minor repairs start around $300, with most repairs ranging $500-$1,500." },
      { q: "Can repairs prevent the need for replacement?", a: "Often yes! Catching damage early and proper repairs can extend your roof life by 5-10+ years." },
    ],
  },

  "storm-damage": {
    title: "Storm Damage",
    emoji: "⛈️",
    color: "#3B82F6",
    tagline: "Emergency Storm Response",
    heroTitle: "Storm Damage Repair Experts",
    heroDescription: "24/7 emergency response for hail, wind, and storm damage. We work directly with your insurance company to handle the entire claims process.",
    quickBenefits: ["24/7 Emergency", "Insurance Help", "Fast Response", "Free Inspection"],
    included: [
      { title: "Emergency Tarping", description: "Immediate protection from further water damage." },
      { title: "Damage Assessment", description: "Detailed inspection with photo documentation." },
      { title: "Insurance Claim", description: "We file and manage your insurance claim." },
      { title: "Adjuster Meeting", description: "We meet with insurance adjuster on your behalf." },
      { title: "Complete Repair", description: "Full restoration once claim is approved." },
      { title: "Final Documentation", description: "All paperwork and warranties provided." },
    ],
    process: [
      { title: "Emergency Call", description: "Call us 24/7 — we respond within 1 hour." },
      { title: "Damage Assessment", description: "Free comprehensive inspection." },
      { title: "Insurance Filing", description: "We handle all insurance paperwork." },
      { title: "Full Restoration", description: "Complete repair or replacement done right." },
    ],
    faqs: [
      { q: "Do you handle insurance claims?", a: "Yes! We work with all major insurance companies and handle the entire claims process for you — from filing to final payment." },
      { q: "How quickly can you respond?", a: "We offer 24/7 emergency response with arrival typically within 1-2 hours for urgent situations." },
      { q: "What if my claim is denied?", a: "We can help appeal denied claims and provide professional damage documentation to support your case." },
      { q: "Will my insurance rates go up?", a: "Most insurance companies don't raise rates for weather-related claims since they're considered 'acts of God.'" },
      { q: "How long do I have to file a claim?", a: "Most policies require filing within 1 year of the storm event, but the sooner the better. We recommend filing within 30 days." },
    ],
  },

  "commercial": {
    title: "Commercial Roofing",
    emoji: "🏢",
    color: "#10B981",
    tagline: "Commercial Roof Solutions",
    heroTitle: "Commercial Roofing Specialists",
    heroDescription: "Flat and commercial roof systems built for businesses. TPO, EPDM, and modified bitumen installations with minimal business disruption.",
    quickBenefits: ["Minimal Disruption", "All Flat Roof Types", "Weekend Work", "20-Year Warranty"],
    included: [
      { title: "Free Site Survey", description: "Complete commercial roof assessment." },
      { title: "TPO Roofing", description: "Energy-efficient white membrane systems." },
      { title: "EPDM Roofing", description: "Durable rubber roofing solutions." },
      { title: "Built-Up Roofing", description: "Traditional multi-layer protection." },
      { title: "Roof Maintenance", description: "Preventative maintenance programs." },
      { title: "Emergency Service", description: "24/7 commercial emergency response." },
    ],
    process: [
      { title: "Site Survey", description: "Detailed inspection and documentation." },
      { title: "Custom Proposal", description: "Tailored solution for your property." },
      { title: "Scheduled Install", description: "Work scheduled to minimize disruption." },
      { title: "Ongoing Support", description: "Maintenance and warranty support." },
    ],
    faqs: [
      { q: "What commercial systems do you install?", a: "We install all major commercial systems including TPO, EPDM, modified bitumen, built-up roofing, and metal roofing." },
      { q: "Will my business be disrupted?", a: "We work hard to minimize disruption with flexible scheduling including evenings and weekends when needed." },
      { q: "Do you offer maintenance contracts?", a: "Yes! Regular maintenance can extend commercial roof life by 50% or more. We offer annual and bi-annual programs." },
      { q: "What warranties are available?", a: "Commercial systems come with 10-30 year manufacturer warranties plus our workmanship warranty." },
    ],
  },

  "gutters": {
    title: "Gutter Services",
    emoji: "💧",
    color: "#06B6D4",
    tagline: "Gutter Installation & Repair",
    heroTitle: "Professional Gutter Services",
    heroDescription: "Seamless aluminum gutter installation, repair, and cleaning. Protect your home's foundation with properly functioning gutters.",
    quickBenefits: ["Seamless Aluminum", "All Colors", "Leaf Guards", "Same-Day Quotes"],
    included: [
      { title: "Seamless Installation", description: "Custom-made on-site to fit your home perfectly." },
      { title: "Multiple Colors", description: "Wide range of colors to match your home." },
      { title: "Leaf Guard Systems", description: "Prevent clogs with quality leaf protection." },
      { title: "Gutter Cleaning", description: "Professional cleaning and debris removal." },
      { title: "Repairs & Realignment", description: "Fix sagging, leaking, or damaged sections." },
      { title: "Downspout Extensions", description: "Direct water away from your foundation." },
    ],
    process: [
      { title: "Free Quote", description: "Same-day quotes available." },
      { title: "Color Selection", description: "Choose from 20+ colors." },
      { title: "Installation", description: "Most jobs completed in 1 day." },
      { title: "Walkthrough", description: "Final inspection together." },
    ],
    faqs: [
      { q: "How often should gutters be cleaned?", a: "We recommend cleaning twice a year — spring and fall — or quarterly if you have many trees nearby." },
      { q: "Are leaf guards worth it?", a: "Yes! Quality leaf guards dramatically reduce cleaning needs and protect your gutters from damage." },
      { q: "What size gutters do I need?", a: "Most homes need 5-inch gutters, but larger homes or areas with heavy rain may need 6-inch. We'll recommend the best size." },
      { q: "How long do gutters last?", a: "Quality aluminum gutters last 20-30 years with proper maintenance." },
    ],
  },
};